main: net.pwing.races.PwingRaces
bootstrapper: net.pwing.races.paper.PwingRacesBootstrapper
name: PwingRaces
description: "A very highly-customizable race plugin for any server!"
version: ${version}
api-version: 1.19
authors: [Redned]
dependencies:
  server:
    WorldEdit:
      required: false
      join-classpath: true
    WorldGuard:
      required: false
      join-classpath: true
    MagicSpells:
      required: false
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true
    Quests:
      required: false
      join-classpath: true
    LibsDisguises:
      required: false
      join-classpath: true
    LoreAttributesRecoded:
      required: false
      join-classpath: true
    Vault:
      required: false
      join-classpath: true